export const ESCUDOS = {
'Flamengo': require('../../assets/escudos/bra/flamengo.png'),
'Botafogo': require('../../assets/escudos/bra/botafogo.png'),
'Vasco': require('../../assets/escudos/bra/vasco.png'),
'Fluminense': require('../../assets/escudos/bra/fluminense.png'),
'Corinthias': require('../../assets/escudos/bra/corinthias.png'),
'Palmeiras': require('../../assets/escudos/bra/palmeiras.png'),
'São Paulo': require('../../assets/escudos/bra/sao_paulo.png'),
'Santos': require('../../assets/escudos/bra/santos.png'),
'Ponte Preta': require('../../assets/escudos/bra/ponte_preta.png'),
'Atlético Mineiro': require('../../assets/escudos/bra/atletico_mg.png'),
'Cruzeiro': require('../../assets/escudos/bra/cruzeiro.png'),
'Grêmio': require('../../assets/escudos/bra/gremio.png'),
'Internacional': require('../../assets/escudos/bra/internacional.png'),
'Barcelona': require('../../assets/escudos/spa/barcelona.png'),
'Real Madrid': require('../../assets/escudos/spa/real_madrid.png'),
'Atletico de Madrid': require('../../assets/escudos/spa/atletico_de_madrid.png'),
'Bayern de Munique': require('../../assets/escudos/ger/bayern_munique.png'),
'Borussia Dortmund': require('../../assets/escudos/ger/borussia_dortmund.png'),
'Chelsea': require('../../assets/escudos/uk/chelsea.png'),
'Arsenal': require('../../assets/escudos/uk/arsenal.png'),
'Tottenham': require('../../assets/escudos/uk/tottenham.png'),
'Liverpool': require('../../assets/escudos/uk/liverpool.png'),
'Manchester City': require('../../assets/escudos/uk/manchester_city.png'),
'Manchester United': require('../../assets/escudos/uk/manchester_united.png'),
'Brazil': require('../../assets/escudos/international/brazil.png'),
'Spain': require('../../assets/escudos/international/spain.png'),
'United Kingdom': require('../../assets/escudos/international/uk.png'),
'Germany': require('../../assets/escudos/international/germany.png')
};
